//
// Created by marcin on 13.11.18.
//

#ifndef PARALLEL_COMPUTING_GENETICALGORITHMENGINE_H
#define PARALLEL_COMPUTING_GENETICALGORITHMENGINE_H


class GeneticAlgorithmEngine {

};


#endif //PARALLEL_COMPUTING_GENETICALGORITHMENGINE_H
